### ISSUE TITLE
whatsapp doesnt work v1.2.1

### ISSUE THREAD

**Issue by xsamsxx** [AbhishekDoshi26/contactus#12]
hi i use the new version 1.2.1 and when i click on the phone number that popupmenu comes out whatsapp doesn't work , the number in phonenumber: is correct  beacuse the other 2 ways call and message they work perfectly

**Comment by AbhishekDoshi26** [comment]
Thanks for pointing out @xsamsxx . I have created a PR for a fix: #13 
Deploying new version soon.

**Comment by AbhishekDoshi26** [comment]
@xsamsxx v1.2.2 has been released :)

**Comment by xsamsxx** [comment]
Could not load webpage at whatsapp://send/?phone=%2Bxxxxxxxxxxx&text&type=phone_number&app_absent=0 because:

 net::ERR_UNKNOWN_URL_SCHEME


thank you for your speed but still gives the same error . the x's represent the phone number

**Comment by AbhishekDoshi26** [comment]
@xsamsxx are you trying on emulator?
I tried on google chrome, it works perfectly and also on real device.

**Comment by xsamsxx** [comment]
real device

**Comment by xsamsxx** [comment]
it could be because the number is linked to whatsapp business?

**Comment by xsamsxx** [comment]
@AbhishekDoshi26

**Comment by AbhishekDoshi26** [comment]
Yes. Probably because of business whatsapp account.

**Comment by AbhishekDoshi26** [comment]
@xsamsxx can you verify in v1.2.3?

Thanks!

**Comment by xsamsxx** [comment]
Yes!! finally work Thank you very very much ,you're great

**Comment by AbhishekDoshi26** [comment]
haha no problem. Hope it helps :)
