### ISSUE TITLE
add tiktok option

### ISSUE THREAD

**Issue by danchengash** [AbhishekDoshi26/contactus#14]

**Comment by Shreemanarjun** [comment]
@AbhishekDoshi26 I want to work on this. Please assign me.

**Comment by AbhishekDoshi26** [comment]
@Shreemanarjun sure go on :)

**Comment by Shreemanarjun** [comment]
Fixed by #15 @AbhishekDoshi26

**Comment by Shreemanarjun** [comment]
Please assign the bug label to hacktoberfest if possible.

**Comment by Imsurajr** [comment]
If the issue is still open, i will like to work on it.

**Comment by AbhishekDoshi26** [comment]
Fixed in #15
