### ISSUE TITLE
Allow users to create a custom field 

### ISSUE THREAD

**Issue by Riktam-Santra** [AbhishekDoshi26/contactus#16]
Right now all parameters are hard coded and there can be a brand/social network which might not be in the options. It will be useful if an option to add a custom field is available

**Comment by Riktam-Santra** [comment]
Please assign me on this issue if you consider it

**Comment by AbhishekDoshi26** [comment]
@Riktam-Santra sure thing. Feel free to work on it :)

**Comment by Riktam-Santra** [comment]
@AbhishekDoshi26 please do review and merge the request before the hacktoberfest period ends
