### ISSUE TITLE
IOS 14- Phone and mail links not working on emulator

### ISSUE THREAD

**Issue by EmirSoza** [AbhishekDoshi26/contactus#2]
I tried on android emulator and all linkings worked well. But I tried on iPhoneSE 2nd generation iOS 14.0 and phone-mail linkings do not work. I will try on real device but I don't have iOS 14.0 but 12.4.8. will let you know if it works or not.

**Comment by EmirSoza** [comment]
It worked on 12.4.8 iPhone 5s real device.

**Comment by AbhishekDoshi26** [comment]
Can you please send the code snippet where you are passing the parameters. @EmirSoza

**Comment by AbhishekDoshi26** [comment]
> I tried on android emulator and all linkings worked well. But I tried on iPhoneSE 2nd generation iOS 14.0 and phone-mail linkings do not work. I will try on real device but I don't have iOS 14.0 but 12.4.8. will let you know if it works or not.

Confirm that the links don't have space.

**Comment by EmirSoza** [comment]
`ContactUs(
          cardColor: Colors.white,
          textColor: Colors.black,
          image: Image.asset('assets/images/logohvit.png',fit: BoxFit.fill,),
          email: 'es@luftfartsmuseum.no',
          emailText: "Gi tilbakemelding",
          websiteText: "Besøk nettside",
          companyName: 'Norsk Luftfartsmuseum',
          companyColor: Colors.white,
          companyFontSize: 18,
          phoneNumber: '+4775507850',
          phoneNumberText: "Ring oss",
          website: 'https://www.luftfartsmuseum.no', 
          taglineColor: Colors.teal.shade100,
          instagram: 'norskluftfartsmuseum',
          facebookHandle: "flymuseum",
        
        ),`

**Comment by AbhishekDoshi26** [comment]
> `ContactUs(
> cardColor: Colors.white,
> textColor: Colors.black,
> image: Image.asset('assets/images/logohvit.png',fit: BoxFit.fill,),
> email: '[es@luftfartsmuseum.no](mailto:es@luftfartsmuseum.no)',
> emailText: "Gi tilbakemelding",
> websiteText: "Besøk nettside",
> companyName: 'Norsk Luftfartsmuseum',
> companyColor: Colors.white,
> companyFontSize: 18,
> phoneNumber: '+4775507850',
> phoneNumberText: "Ring oss",
> website: 'https://www.luftfartsmuseum.no',
> taglineColor: Colors.teal.shade100,
> instagram: 'norskluftfartsmuseum',
> facebookHandle: "flymuseum",
> 
> ```
>     ),`
> ```

Instead of ' ' (single quote)
Use " " (double quote)

**Comment by AbhishekDoshi26** [comment]
> `ContactUs(
> cardColor: Colors.white,
> textColor: Colors.black,
> image: Image.asset('assets/images/logohvit.png',fit: BoxFit.fill,),
> email: '[es@luftfartsmuseum.no](mailto:es@luftfartsmuseum.no)',
> emailText: "Gi tilbakemelding",
> websiteText: "Besøk nettside",
> companyName: 'Norsk Luftfartsmuseum',
> companyColor: Colors.white,
> companyFontSize: 18,
> phoneNumber: '+4775507850',
> phoneNumberText: "Ring oss",
> website: 'https://www.luftfartsmuseum.no',
> taglineColor: Colors.teal.shade100,
> instagram: 'norskluftfartsmuseum',
> facebookHandle: "flymuseum",
> 
> ```
>     ),`
> ```

The code is perfect. May be it's problem of emulator.

**Comment by EmirSoza** [comment]
Doesn't work. But I think its not about code or package. I just wonder if would worked on real iOS 14.0 device. Thank you for close support :))

**Comment by AbhishekDoshi26** [comment]
Hey @EmirSoza i just read the docs. Flutter didn't had support for IOS 14. In the recent release of Flutter 1.22, they provided IOS 14 support. So to run the app on IOS 14, you need to update your Flutter SDK.
