### ISSUE TITLE
when i click anything its not working!

### ISSUE THREAD

**Issue by rameshkumar-rk** [AbhishekDoshi26/contactus#4]
For example click website it is not redirecting to website

**Comment by AbhishekDoshi26** [comment]
> For example click website it is not redirecting to website

Can you please share the code snippet where you use Contactus. Also share the error that is shown in console when you click.
@rameshkumar-rk

**Comment by AbhishekDoshi26** [comment]
Closing due to:
- Lack of information provided.
- Lack of communication.
