### ISSUE TITLE
whatsAppNumber nummber 

### ISSUE THREAD

**Issue by asadullahkhan** [AbhishekDoshi26/contactus#9]
On aading whatsapp  number giving error

**Comment by AbhishekDoshi26** [comment]
@asadullahkhan Please provide a reproducible code snippet and the error that you are getting.

Thanks!

**Comment by AbhishekDoshi26** [comment]
Closing due to lack of response

**Comment by asadullahkhan** [comment]
email: 'abc@gmail.com',
          companyName: 'abc',
          companyColor: Colors.teal.shade900,
          phoneNumber: '9898989898',
          //whatsAppNumber: '+91-8512121212',
          //website: 'https://.com',
          //githubUserName: '',
          //linkedinURL: 'https://www.linkedin.com/in/',
          //tagLine: ' ',

**Comment by AbhishekDoshi26** [comment]
@asadullahkhan Don't add '-' between number. So it should be:
whatsAppNumber: '+918512121212',

**Comment by asadullahkhan** [comment]
I have added WhatsApp number in your library. Now it is working fine.
Please update it in your library.
